import os
import re

# File paths
c_srt_path = r"c:\Users\Public\doanh\code\tool\dichvideo\srt-khoahoc\c-srt.srt"
c_srt_out_path = r"c:\Users\Public\doanh\code\tool\dichvideo\srt-khoahoc\c-srt_vi.srt"

c_srt_1_path = r"c:\Users\Public\doanh\code\tool\dichvideo\srt-khoahoc\c-srt(1).srt"
c_srt_1_out_path = r"c:\Users\Public\doanh\code\tool\dichvideo\srt-khoahoc\c-srt(1)_vi.srt"

# Conan translations mapping (1-indexed based on segment number)
conan_translations = {
    1: "Nếu đi vệ sinh xong mà phát hiện hết giấy,",
    2: "bạn sẽ làm thế nào?",
    3: "Ông chú Mouri",
    4: "lúc này đang rơi vào một tình cảnh",
    5: "vô cùng khó xử và oái oăm.",
    6: "Giấy vệ sinh đã hết sạch!",
    7: "Nếu là ngày thường,",
    8: "ông chú đã hét toáng lên gọi cô con gái rượu mang giấy vào.",
    9: "Nhưng hôm nay thì tuyệt đối không thể!",
    10: "Bởi vì nữ thần trong mộng của ông,",
    11: "cô ca sĩ Yoko đang ngồi ở phòng khách bên ngoài.",
    12: "Không thể để thần tượng biết mình đi vệ sinh mà không có giấy được.",
    13: "Ông chú thà nhịn chứ quyết không mở lời.",
    14: "Dù có thể gọi điện thoại,",
    15: "nhưng nếu bị Ran trêu chọc trước mặt Yoko,",
    16: "thì chuyện xấu hổ này chẳng phải cũng bị lộ sao?",
    17: "Đúng lúc này,",
    18: "Mouri sực nhớ tới nhóc kính cận Conan,",
    19: "có thể gửi tin nhắn nhờ nhóc giúp đỡ.",
    20: "Để tránh tin nhắn bị người khác nhìn thấy,",
    21: "ông chú còn cẩn thận mã hóa nó.",
    22: "Nào ngờ, chính hành động này của ông",
    23: "lại tình cờ phá được một vụ án bí ẩn trên gác mái.",
    24: "Hôm ấy, cô Yoko ghé thăm văn phòng thám tử",
    25: "nhờ Mouri làm sáng tỏ một vụ việc kỳ lạ.",
    26: "Trước đó, cô có đến một căn biệt thự để quay phim,",
    27: "nơi đó khá âm u và đáng sợ,",
    28: "cực kỳ hợp với vai diễn thám tử tâm linh của cô.",
    29: "Chủ nhân căn biệt thự",
    30: "là Nukiyasu, anh rể của nhà sản xuất Heijima.",
    31: "Chị gái của Heijima từng mất tích trong căn nhà này,",
    32: "đến nay vẫn bặt vô âm tín.",
    33: "Đúng vào đêm xảy ra sự việc,",
    34: "Yoko nghe thấy tiếng động ở hành lang",
    35: "nên liền ra ngoài kiểm tra.",
    36: "Cô thấy trên sàn có những giọt siro màu đỏ,",
    37: "liền lần theo dấu vết đến góc rẽ,",
    38: "nhưng vết đỏ bỗng nhiên biến mất.",
    39: "Cùng lúc đó,",
    40: "chủ nhà là Nukiyasu cũng biến mất.",
    41: "Mọi người vội vàng tìm kiếm khắp nơi. Cậu em trai Fuugo",
    42: "còn lấy điện thoại của vợ gọi cho anh trai,",
    43: "nhưng không ai bắt máy.",
    44: "Điều kỳ lạ hơn là,",
    45: "sau đó,",
    46: "Fuugo nhận được một bức ảnh do anh trai gửi tới,",
    47: "chụp một đống bài Tây lộn xộn,",
    48: "không ai hiểu có ý nghĩa gì.",
    49: "Mãi đến 4 ngày sau,",
    50: "Fuugo mới nhớ ra",
    51: "lúc nhỏ anh em họ thường lén chơi bài trên gác mái,",
    52: "ở đó vẫn còn sót lại rất nhiều bộ bài.",
    53: "Vì không hạ được thang gác mái xuống,",
    54: "cảnh sát đành phải phá khóa cửa sổ gác mái,",
    55: "và phát hiện Nukiyasu bị trúng một mũi tên từ phía sau,",
    56: "và đã ra đi mãi mãi.",
    57: "Câu hỏi đặt ra là,",
    58: "làm thế nào kẻ thủ ác có thể giam nạn nhân trong căn phòng gác mái khóa kín?",
    59: "Hơn nữa, nếu nạn nhân gửi được ảnh bài Tây,",
    60: "tại sao lại không gọi điện cầu cứu?",
    61: "Không còn cách nào khác, cô Yoko",
    62: "mới phải tìm đến thám tử Mouri.",
    63: "Ông chú nghe xong thì vô cùng hào hứng,",
    64: "định vỗ ngực cam đoan sẽ phá được án.",
    65: "Nhưng bỗng nhiên bụng đau quằn quại,",
    66: "mặt tái mét lao ngay vào nhà vệ sinh.",
    67: "Thế là câu đố hóc búa này,",
    68: "đương nhiên được chuyển giao cho Conan",
    69: "và bác đầu bếp Wakita vừa khéo mang sushi tới.",
    70: "Hứng thú của bác đầu bếp với vụ việc này",
    71: "rõ ràng lớn hơn nhiều so với việc giao hàng.",
    72: "Theo lời kể của Yoko,",
    73: "mối quan hệ giữa các nhân vật dần hé lộ.",
    74: "Chủ nhà Nukiyasu là anh cả,",
    75: "người em Fuugo bị trật khớp tay trái,",
    76: "cô em dâu Himi phải ngồi xe lăn,",
    77: "và cậu em vợ Heijima",
    78: "thì phải chống nạng, tạo nên một nhóm người ai nấy đều thương tích đầy mình.",
    79: "Chỉ có mỗi Yoko là người lành lặn.",
    80: "Hai năm trước, người vợ Houka của Nukiyasu",
    81: "đã biến mất một cách bí ẩn ngay tại biệt thự này,",
    82: "không để lại bất kỳ dấu vết nào.",
    83: "Điều đáng nói, mối tình đầu của Fuugo chính là chị dâu Houka,",
    84: "còn Himi lại là bạn thân của Houka.",
    85: "Mối quan hệ tay ba phức tạp này",
    86: "khiến ai cũng có lý do để ra tay với Nukiyasu.",
    87: "Thế nhưng có một điểm rất lạ,",
    88: "trước khi mất tích, bà Houka luôn đeo kính râm,",
    89: "dù trước đây bà chưa từng có thói quen này.",
    90: "Manh mối duy nhất chỉ có bức ảnh bài Tây,",
    91: "trong ảnh xuất hiện nhiều lá bài trùng lặp,",
    92: "trông thì có vẻ ngẫu nhiên,",
    93: "nhưng thực chất lại ẩn giấu bí mật.",
    94: "Ngoài ra,",
    95: "cô Yoko nhớ ra một chi tiết,",
    96: "khi nhà sản xuất Heijima vừa tới đây đã nói,",
    97: "hàng thông bên ngoài biệt thự so với 3 năm trước",
    98: "đã bị thiếu mất một cây.",
    99: "Lúc đó, Nukiyasu giải thích rằng",
    100: "ông ta đã bứng cây đó chuyển đi nơi khác.",
    101: "Biết thêm nhiều thông tin,",
    102: "nhưng mọi người vẫn bế tắc.",
    103: "Lúc này trong nhà vệ sinh, Mouri cũng như ngồi trên đống lửa.",
    104: "Vì hết giấy vệ sinh,",
    105: "mà để giữ thể diện trước mặt Yoko,",
    106: "ông không thể gọi với ra bảo Ran mang vào.",
    107: "Thế là ông nghĩ tới Conan,",
    108: "lập tức dùng điện thoại gửi đi một mật mã cầu cứu.",
    109: "Nhận được tin nhắn, Conan mở ra xem,",
    110: "nội dung là hai dòng ký tự gồm số và chữ Hán ghép lại.",
    111: "Ran nhanh mắt nhận ra ngay,",
    112: "đây chính là các thế bài trong mạt chược.",
    113: "Nghe vậy, Conan và bác Wakita lập tức bừng tỉnh.",
    114: "Cả hai nhận ra,",
    115: "việc thám tử Mouri gửi mật mã cầu cứu",
    116: "giống hệt như trường hợp của Nukiyasu bị kẹt trên gác mái.",
    117: "Hai việc này thực chất hoàn toàn tương đồng.",
    118: "Đều vì một lý do khó nói nào đó",
    119: "mà không thể trực tiếp kêu cứu,",
    120: "chỉ đành phải gửi gắm qua các ký hiệu bí ẩn.",
    121: "Hóa ra là vậy!",
    122: "Cả hai đều đã hiểu thông suốt.",
    123: "Lần theo manh mối này, Conan",
    124: "xem xét lại bức ảnh bài Tây,",
    125: "dịch tên các chất bài ra tiếng Anh,",
    126: "rồi dựa vào con số trên lá bài",
    127: "để lấy ra chữ cái ở vị trí tương ứng.",
    128: "Lá 1 Cơ (Heart) lấy chữ cái thứ nhất là H.",
    129: "Lá 2 Cơ lấy chữ thứ hai là E.",
    130: "Lá 2 Nhép (Club) lấy chữ thứ hai là L.",
    131: "Lá 2 Bích (Spade) lấy chữ thứ hai là P.",
    132: "Ghép lại ta được từ \"HELP\" (Cứu với).",
    133: "Các bộ bài tiếp theo cũng giải mã tương tự,",
    134: "được chữ \"ATTIC\" (Gác mái).",
    135: "Hai bộ sau là chữ \"ANNA\" và \"IRU\" (tiếng Nhật nghĩa là có mặt ở đây).",
    136: "Tổng hợp lại nghĩa là: \"Cứu tôi với,",
    137: "tôi đang ở trên gác mái\".",
    138: "Nhưng điểm mấu chốt và đáng sợ nhất là,",
    139: "bộ bài cuối cùng",
    140: "lại giải ra nội dung:",
    141: "Thủ phạm chính là Himi.",
    142: "Bác Wakita nhận định, dù người em dâu phải ngồi xe lăn,",
    143: "nhưng cô ấy vẫn có thể dùng thiết bị bắn tên,",
    144: "chỉ cần giấu nó dưới tấm chăn đắp đùi.",
    145: "Đêm đó, thủ phạm dụ Nukiyasu ra hành lang",
    146: "rồi bắn một mũi tên từ phía sau lưng ông ta.",
    147: "Tuy nhiên, cú bắn không khiến nạn nhân ra đi ngay lập tức.",
    148: "Nukiyasu ôm vết thương bỏ chạy,",
    149: "còn Himi thì lăn xe lăn đuổi theo sát nút.",
    150: "Khi nghe tiếng động, Yoko lần theo vết đỏ chạy tới,",
    151: "Himi liền dừng lại,",
    152: "dùng chân kéo tấm chăn dưới bánh xe lăn",
    153: "để lau sạch vệt đỏ trên sàn.",
    154: "Đó chính là lý do tại sao vết siro đỏ",
    155: "lại đột ngột biến mất ở khúc quanh.",
    156: "Himi cố tình dồn ép Nukiyasu chạy lên gác mái,",
    157: "vì biết rõ nơi đó là một chiếc lồng giam hoàn hảo.",
    158: "Sau đó, cô tỏ ra như không có chuyện gì,",
    159: "thậm chí còn lớn tiếng gọi tìm anh trai.",
    160: "But that was not searching,",
    161: "but a naked threat:",
    162: "\"Nếu dám bước xuống, tôi sẽ cho thêm một mũi tên nữa.\"",
    163: "Nukiyasu không dám gọi điện báo cảnh sát,",
    164: "bởi một khi cảnh sát can thiệp,",
    165: "tội ác hãm hại người vợ cũ của ông ta cũng sẽ bị phanh phui.",
    166: "Người vợ Houka vốn không bao giờ đeo kính râm,",
    167: "nhưng 2 năm trước lại đột ngột đeo liên tục,",
    168: "mục đích là để che đi những vết bầm tím trên mặt,",
    169: "chưng tỏ bà đã bị ông chồng bạo hành dã man.",
    170: "Nukiyasu vì muốn bảo toàn mạng sống,",
    171: "mới gửi mật mã cho cậu em Fuugo cứu giúp.",
    172: "Vốn chơi bài cùng nhau từ nhỏ,",
    173: "người em chắc chắn đã hiểu ý nghĩa bức ảnh,",
    174: "nhưng anh ta lại chọn cách im lặng.",
    175: "Anh ta còn nói dối là điện thoại hết pin,",
    176: "rồi dùng máy của vợ gọi vào số anh trai.",
    177: "Nhìn thấy cuộc gọi từ số của thủ phạm (Himi),",
    178: "Nukiyasu tất nhiên không dám nghe máy.",
    179: "Nguồn cơn sự thờ ơ của người em",
    180: "chính là lòng căm thù gã anh trai vũ phu,",
    181: "bởi chị dâu Houka vốn là mối tình đầu của anh ta.",
    182: "Hai năm trước,",
    183: "Nukiyasu sau khi tiễn vợ mình bay màu đã nói dối là vợ mất tích.",
    184: "Để che đậy hành vi xấu,",
    185: "ông ta lấy cớ bứng cây thông đi nơi khác",
    186: "để giấu người quá cố dưới hố sâu.",
    187: "Là bạn thân của Houka,",
    188: "Himi sớm đã nghi ngờ Nukiyasu,",
    189: "nên mới dùng mũi tên ép ông ta nói ra sự thật.",
    190: "Đó là lý do Nukiyasu khi bị hãm hại lại không dám hé răng báo cảnh sát,",
    191: "bởi vì bản thân ông ta cũng là kẻ gieo rắc tai họa.",
    192: "Chỉ cần cảnh sát tìm thấy dấu vết",
    193: "dưới hố cây thông bị bứng đi,",
    194: "thì vụ án này sẽ chính thức khép lại.",
    195: "Còn về mật mã xin giấy vệ sinh của Mouri,",
    196: "Conan cũng đã làm sáng tỏ.",
    197: "Đó là tên hai thế bài mạt chược:",
    198: "Hàng đầu là \"Thập Tam Thái Tử\" (Thập Tam Yêu),",
    199: "đang đợi quân \"Bắc\" (North) để thắng.",
    200: "Hàng thứ hai là \"Cửu Liên Bảo Đăng\",",
    201: "đang đợi quân \"Bát\" (8) để thắng.",
    202: "Ghép hai quân \"Bắc\" và \"Bát\" phát âm chệch đi thành \"Paper\" (Giấy).",
    203: "Ám chỉ ông chú đang cực kỳ cần giấy vệ sinh!",
    204: "Trò đùa mật mã dở khóc dở cười do đau bụng này",
    205: "cuối cùng",
    206: "lại trở thành mảnh ghép quan trọng để phá giải vụ án bí mật hoàn hảo.",
    207: "Đúng là trong thế giới của Conan,",
    208: "ngay cả nhà vệ sinh cũng chứa đựng chân lý!"
}

# Shin-chan translations mapping
shin_translations = {
    1: "Ở thời tiền sử, bố Hiroshi có thể ngủ nướng đến tận trưa muộn.",
    2: "Vừa thức dậy, mẹ Misae đã chuẩn bị món trứng voi ma mút rán cho bữa sáng.",
    3: "Nhưng dù mẹ Misae có gọi thế nào, bố Hiroshi vẫn lười không chịu dậy đi săn.",
    4: "Hết cách, mẹ Misae đành dùng gậy gai \"dạy dỗ\" ông chồng một trận.",
    5: "Sau đó, cu Shin cũng bị thức tỉnh bởi thiết quyền của mẹ.",
    6: "Thấy hôm nay cu cậu không tè dầm,",
    7: "mẹ Misae định thưởng cho một phần",
    8: "trứng voi ma mút rán.",
    9: "Vui sướng quá, ai dè cu Shin lại nhịn không được mà tè luôn ra sàn.",
    10: "Vệ sinh xong xuôi, cả nhà bắt đầu dùng bữa sáng.",
    11: "Trứng voi ma mút rán thơm lừng,",
    12: "lại còn được uống thêm sữa voi ma mút tươi.",
    13: "Trước khi bố Hiroshi đi săn,",
    14: "mẹ Misae còn chu đáo đưa cho ông chồng 1 vạn tiền đá.",
    15: "Số tiền tiêu vặt này quá nặng nề,",
    16: "bố Hiroshi chỉ muốn vứt bớt đi cho nhẹ.",
    17: "Cu Shin thì mè nheo đòi mua bộ đồ Siêu nhân Hành động.",
    18: "Mẹ Misae thấy cu cậu quá hoang phí,",
    19: "liền tặng ngay cho một gậy vào đầu.",
    20: "Mẹ nhắc Shin mau thay quần áo,",
    21: "xe của trường mẫu giáo sắp đến rồi.",
    22: "Đằng xa vang lên tiếng heo kêu éc éc,",
    23: "cô Yoshinaga lái chiếc xe heo rừng",
    24: "đã đến trước cửa nhà Nohara.",
    25: "Thế nhưng lúc này cu Shin lại đang bị táo bón.",
    26: "Xem ra dù là ở thời hiện đại hay thời cổ đại,",
    27: "cu Shin vẫn không tài nào sửa được tật đi học trễ.",
    28: "Hết cách, mẹ Misae đành bảo cô Yoshinaga đi trước,",
    29: "rồi tự mình dùng chiếc xe trượt tự chế",
    30: "để chở cu cậu tới trường.",
    31: "May mà tốc độ của mẹ Misae cực nhanh,",
    32: "cuối cùng cũng đến được trường mẫu giáo Futaba.",
    33: "Hôm nay cả lớp học tiết Mỹ thuật,",
    34: "các bạn nhỏ đang cặm cụi điêu khắc trên đá.",
    35: "Riêng cậu nhóc Kazama cực kỳ sáng tạo,",
    36: "dùng màu nhuộm vẽ tranh trên phiến đá,",
    37: "khiến cả lớp ngưỡng mộ không thôi.",
    38: "Vừa đi học về đến nhà,",
    39: "mẹ Misae đã xách túi tiền 1 vạn chuẩn bị ra ngoài mua đồ ăn.",
    40: "Shin vừa nghe thấy liền đòi đi theo bằng được.",
    41: "Mẹ Misae đành phải dắt Shin đi cùng.",
    42: "Cơ mà mới đi được một đoạn ngắn,",
    43: "cu Shin đã rên rỉ kêu mỏi chân.",
    44: "May mắn là cả hai cũng đến được khu chợ tiền sử.",
    45: "Ở đây có vô vàn món ăn ngon,",
    46: "ngay cả thịt voi ma mút nướng cũng có luôn.",
    47: "Lại còn được ăn thử miễn phí nữa chứ.",
    48: "Vốn là tâm hồn ăn uống, mẹ Misae",
    49: "lập tức xông vào ăn thử liền tù tì mấy xiên liền.",
    50: "Đang đi thì tai nạn xảy ra,",
    51: "tiền của mẹ Misae đột nhiên bị rơi xuống đất.",
    52: "Nhìn thấy phía trước có gian hàng giảm giá sốc,",
    53: "mẹ dặn Shin đứng im một chỗ trông chừng tiền,",
    54: "còn bản thân thì lao thẳng vào khu giảm giá.",
    55: "Cu Shin ở lại thấy chị gái xinh đẹp đi qua liền chạy tới bắt chuyện ghẹo gái.",
    56: "Nhìn thấy ai trông ngứa mắt đi qua,",
    57: "cu cậu lại làm mặt dữ tợn dọa dẫm.",
    58: "Ngay cả khi mẹ Misae đã quay lại,",
    59: "cu Shin vẫn cứ nhe răng trợn mắt gầm gừ.",
    60: "Quả này chắc chắn là có thù hằn cá nhân gì đây mà.",
    61: "Mua đồ xong, tờ 1 vạn được thối lại một đống tiền đá lẻ,",
    62: "làm mẹ Misae xách nặng trĩu tay.",
    63: "Trên đường về nhà,",
    64: "Shin phát hiện bên đường có một chú cún đáng thương bị bỏ rơi,",
    65: "trông vô cùng tội nghiệp.",
    66: "Shin rất muốn nhận nuôi chú cún này.",
    67: "Mẹ Misae ban đầu từ chối vì nuôi chó rất phiền phức,",
    68: "nhưng trước lời hứa của Shin là sẽ dắt chó đi dạo mỗi ngày,",
    69: "mẹ cũng đành đồng ý.",
    70: "Shin vừa vẫy tay gọi Bạch Tuyết,",
    71: "cu cậu đã tự giật đứt dây xích trói buộc.",
    72: "Khi chú chó chạy lại gần thì mới vỡ lẽ,",
    73: "nguyên lai đây lại là một chú chó khổng lồ.",
    74: "Shin bảo Bạch Tuyết phải cảm ơn mẹ Misae đàng hoàng.",
    75: "Ngay giây tiếp theo,",
    76: "Bạch Tuyết liếm yêu một phát lên má mẹ Misae.",
    77: "Mẹ Misae hoàn toàn sụp đổ,",
    78: "bắt Shin phải đem vứt trả Bạch Tuyết ngay,",
    79: "đồng thời tiện tay đi nhặt ít củi khô mang về.",
    80: "Đằng nào cũng sắp phải chia tay nhau,",
    81: "nên trước lúc đó,",
    82: "Shin",
    83: "hy vọng Bạch Tuyết có thể giúp mình thồ đống củi về nhà.",
    84: "Cách làm là cắm từng khúc củi vào bộ lông dày cộp của nó là xong.",
    85: "Lúc này, bố Hiroshi đang hớt hải chạy thục mạng về nhà.",
    86: "Vừa về đến nơi, bố lập tức giục mẹ mau trốn đi,",
    87: "có một con voi ma mút điên cuồng sắp tấn công bộ tộc.",
    88: "Trong khi đó, Shin đang cưỡi trên lưng Bạch Tuyết thong thả về nhà.",
    89: "Một con voi ma mút khổng lồ lù lù xuất hiện trước mặt,",
    90: "hai vợ chồng muốn đến ứng cứu nhưng không kịp nữa rồi.",
    91: "Ngay cả Bạch Tuyết cũng hồn xiêu phách lạc,",
    92: "liền co rúm người lại thành một quả bóng tròn xoe.",
    93: "Trong lúc run rẩy bần bật,",
    94: "toàn bộ số củi cắm trên lông của nó rơi rụng lả tả.",
    95: "Vừa lúc đống củi rơi vương vãi khắp mặt đất,",
    96: "con voi ma mút lao lên tấn công.",
    97: "Nào ngờ nó giẫm phải đống củi trơn trượt,",
    98: "thế là đo đất nằm chỏng gọng bốn chân lên trời.",
    99: "Bạch Tuyết bỗng dưng lập công lớn cứu sống cả bộ tộc.",
    100: "Trong buổi tiệc ăn mừng tối hôm đó,",
    101: "bố Hiroshi và mẹ Misae đã thưởng cho Bạch Tuyết",
    102: "một chiếc đùi voi",
    103: "ma mút nướng siêu to khổng lồ, và chính thức nhận nuôi chú cún."
}

def translate_srt(in_path, out_path, mapping):
    with open(in_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Normalize line endings
    content = content.replace('\r\n', '\n')
    
    blocks = content.split('\n\n')
    out_blocks = []
    for block in blocks:
        if not block.strip():
            continue
        lines = block.split('\n')
        if len(lines) >= 3:
            index_str = lines[0].strip()
            timestamp = lines[1].strip()
            try:
                idx = int(index_str)
                translated = mapping.get(idx)
                if translated is None:
                    translated = "\n".join(lines[2:])
            except Exception:
                translated = "\n".join(lines[2:])
            
            out_blocks.append(f"{index_str}\n{timestamp}\n{translated}")
        else:
            out_blocks.append(block)
            
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write("\n\n".join(out_blocks) + "\n\n")
    print(f"Translated {in_path} to {out_path}")

translate_srt(c_srt_path, c_srt_out_path, conan_translations)
translate_srt(c_srt_1_path, c_srt_1_out_path, shin_translations)
